server:
  port: 9527
spring:
  application:
    name: lottery-Gateway
  cloud:
    nacos:
      discovery:
        server-addr: 1.15.86.246:8848
    gateway:
      discovery:
        locator:
          enabled: false
      routes:
        - id: strategy-route
          uri: lb://lottery-strategy
          predicates:
            - Path=/rpc/**
